### ISSUE TITLE
IP address captured is worker node IP instead of user IP

### ISSUE THREAD

**Issue by rameshlohala** [PostHog/charts-clickhouse#132]
## Bug description

The IP address captured in the events is Kubernetes worker node instead of the user's IP address. 

I had also tried enabling proxy protocol to ELB following this documentation https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html

Posthog is deployed on AWS EKS.

![IP](https://user-images.githubusercontent.com/9413979/134872318-328bb6d4-2f13-4382-9610-24170ce6fd9e.png)

## Expected behavior
1. IP address captured in the events should be user's public IP

## Environment

- Deployment platform: aws
- Chart version/commit: 3.12.0
- Posthog version: 1.28.0

**Comment by guidoiaquinti** [comment]
👋 Hi @rameshlohala, thank you for your report. 

I was able to reproduce your issue and it seems to be due to how the AWS ELB (classic) works. In order to fix the issue, can you try to:

1. enable the `PROXY` protocol for the ELB (see official [AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html#enable-proxy-protocol-cli))
2. add this snippet to your `values.yaml` and run a `helm upgrade`:
    ```
    # For AWS ELB in L4 (TCP) mode, we need to enable some additional config
    # in the ingress controller in order to get the proper IP address forwarded
    # to our app. Otherwise we'll get the load balancer nodes addresses instead.
    #
    # See: https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address
    ingress-nginx:
      controller:
        config:
          use-proxy-protocol: true
    ```

?

It should fix your issue.
