### ISSUE TITLE
Improved support for deployments with a different name

### ISSUE THREAD

**Issue by taobojlen** [PostHog/charts-clickhouse#206]
### Proposed change

When deploying to a name other than `posthog`, e.g. `my-posthog-deployment`, we had to add the following config:
```
  kafka:
    externalZookeeper:
      servers:
        - "my-posthog-deployment-posthog-zookeeper:2181"
```

It would be nice if this was handled automatically.

### Alternative options

Perhaps just some documentation would be helpful; it took a little while to debug this.
