### ISSUE TITLE
AWS: Kubernetes Ingress Controller Fake Certificate being used

### ISSUE THREAD

**Issue by killion** [PostHog/charts-clickhouse#247]
## Bug description
I'm creating a new AWS install of Posthog, the Preflight has all green checks but when I go to the install I see the self-signed cert instead of a Lets Encrypt one.

## Expected behavior
I expected that a Lets Encrypt certificate for ph.suiteness.com would be generated.

## Actual behavior
When I go to https://ph.suiteness.com the certificate served is the "Kubernetes Ingress Controller Fake Certificate"

## How to reproduce
1. Follow the build instructions at https://posthog.com/docs/self-host/deploy/aws
2. Use the following values.yaml...
```
cloud: "aws"
ingress:
  hostname: ph.suiteness.com
  nginx:
    enabled: true
cert-manager:
  enabled: true

#
# For AWS ELB in L4 (TCP) mode, we need to enable some additional config
# in the ingress controller in order to get the proper IP address forwarded
# to our app. Otherwise we'll get the load balancer nodes addresses instead.
#
# ref:
#   - https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address
#   - https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
#
ingress-nginx:
  controller:
    config:
      use-proxy-protocol: true
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```
3. Go to https://ph.suiteness.com and examine the certificate.

## Environment

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): _please provide_
- [ ] k8s version (server version from `kubectl version`): _please provide_
- [ ] Chart version/commit (`helm list -n posthog`): _please provide_
- [ ] Posthog version: _please provide_

## Additional context
I have ph.suiteness.com setup as a CNAME to the AWS load balancer with the Cloudflare proxy turned off. After this is working I'd like to turn the Cloudflare proxy on.

I'm currently using Posthog on Heroku and love it. Thank you for the great work!
