### ISSUE TITLE
`Ingress` configuration improvements

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/charts-clickhouse#293]
### Proposed change
Since Kubernetes 1.18 it's recommended to provide the ingress-controller config via the new field `ingressClassName`. All the ingress class annotations (like `kubernetes.io/ingress.class`) are currently deprecated. 

We should change the chart to follow the current best practices

```
ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  labels: {}
  ....
```

### Alternative options
Do nothing.

## Additional context
- https://kubernetes.io/docs/concepts/services-networking/ingress/
- https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/
- https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
