### ISSUE TITLE
Invalid PostgreSQL version range

### ISSUE THREAD

**Issue by gajus** [PostHog/charts-clickhouse#412]
Current deployment is failing with:

```
Service postgresql is in version 14.3.0. Expected range: >=11.0.0,<=14.1.0. PostHog may not work correctly with the current version. To continue anyway, add SKIP_SERVICE_VERSION_REQUIREMENTS=1 as an environment variable
Service postgresql is in version 14.3.0. Expected range: >=11.0.0,<=14.1.0. PostHog may not work correctly with the current version. To continue anyway, add SKIP_SERVICE_VERSION_REQUIREMENTS=1 as an environment variable
```

While I can workaround this using `SKIP_SERVICE_VERSION_REQUIREMENTS`, it makes little sense to exclude minor releases from semver range, i.e. the range should allow `>=11,<15`.

**Comment by gajus** [comment]
Actually, it looks like `SKIP_SERVICE_VERSION_REQUIREMENTS` is ignored.

```
plugins:
  env:
    # This is in place to workaround PostgreSQL incompatibility:
    # Service postgresql is in version 14.3.0. Expected range: >=11.0.0,<=14.1.0.
    # PostHog may not work correctly with the current version.
    # To continue anyway, add SKIP_SERVICE_VERSION_REQUIREMENTS=1 as an environment variable
    - name: SKIP_SERVICE_VERSION_REQUIREMENTS
      value: 'true'
```
