### ISSUE TITLE
Sync is failing with multiple web.env entries

### ISSUE THREAD

**Issue by gajus** [PostHog/charts-clickhouse#416]
`values.yaml`:

```yaml
clickhouse:
  persistentVolumeClaim: 'clickhouse-pvc'
cloud: gcp
events:
  replicacount: 5
ingress:
  enabled: false
  # https://github.com/PostHog/charts-clickhouse/issues/409
  type: 'disabled'
kafka:
  externalZookeeper:
    servers:
      - contra-posthog-posthog-zookeeper:2181
notificationEmail: ci@contra.com
pgbouncer:
  env:
    - name: SERVER_TLS_SSLMODE
      value: 'require'
service:
  type: ClusterIP
web:
  env:
    - name: SITE_URL
      value: 'https://posthog.contra.com'
    - name: TRUST_ALL_PROXIES
      value: 'True'
  replicacount: 5
worker:
  replicacount: 5
```

Helm error when trying to deploy:

```
one or more objects failed to apply, reason: The order in patch list: [map[name:SITE_URL value:http://127.0.0.1:8000] map[name:SITE_URL value:https://posthog.contra.com] map[name:SENTRY_DSN value:<nil>] map[name:EMAIL_HOST value:] map[name:EMAIL_PORT value:] map[name:EMAIL_HOST_USER value:] map[name:DEFAULT_FROM_EMAIL value:<nil>]] doesn't match $setElementOrder list: [map[name:KAFKA_ENABLED] map[name:KAFKA_HOSTS] map[name:KAFKA_URL] map[name:POSTHOG_REDIS_HOST] map[name:POSTHOG_REDIS_PORT] map[name:POSTHOG_REDIS_PASSWORD] map[name:SITE_URL] map[name:DEPLOYMENT] map[name:SENTRY_DSN] map[name:DISABLE_SECURE_SSL_REDIRECT] map[name:IS_BEHIND_PROXY] map[name:SECRET_KEY] map[name:PRIMARY_DB] map[name:POSTHOG_POSTGRES_HOST] map[name:POSTHOG_POSTGRES_PORT] map[name:POSTHOG_DB_USER] map[name:POSTHOG_DB_NAME] map[name:POSTHOG_DB_PASSWORD] map[name:USING_PGBOUNCER] map[name:CLICKHOUSE_HOST] map[name:CLICKHOUSE_CLUSTER] map[name:CLICKHOUSE_DATABASE] map[name:CLICKHOUSE_USER] map[name:CLICKHOUSE_PASSWORD] map[name:CLICKHOUSE_SECURE] map[name:CLICKHOUSE_VERIFY] map[name:EMAIL_HOST] map[name:EMAIL_PORT] map[name:EMAIL_HOST_USER] map[name:EMAIL_HOST_PASSWORD] map[name:EMAIL_USE_TLS] map[name:EMAIL_USE_SSL] map[name:DEFAULT_FROM_EMAIL] map[name:CAPTURE_INTERNAL_METRICS] map[name:HELM_INSTALL_INFO] map[name:SITE_URL]],The order in patch list: [map[name:SITE_URL value:https://posthog.contra.com] map[name:SITE_URL value:http://127.0.0.1:8000] map[name:SENTRY_DSN value:<nil>] map[name:SAML_ENTITY_ID value:] map[name:SAML_ACS_URL value:] map[name:SAML_X509_CERT value:] map[name:SAML_ATTR_PERMANENT_ID value:] map[name:SAML_ATTR_FIRST_NAME value:] map[name:SAML_ATTR_LAST_NAME value:] map[name:SAML_ATTR_EMAIL value:] map[name:EMAIL_HOST value:] map[name:EMAIL_PORT value:] map[name:EMAIL_HOST_USER value:] map[name:DEFAULT_FROM_EMAIL value:<nil>]] doesn't match $setElementOrder list: [map[name:KAFKA_ENABLED] map[name:KAFKA_HOSTS] map[name:KAFKA_URL] map[name:POSTHOG_REDIS_HOST] map[name:POSTHOG_REDIS_PORT] map[name:POSTHOG_REDIS_PASSWORD] map[name:SITE_URL] map[name:DEPLOYMENT] map[name:SENTRY_DSN] map[name:DISABLE_SECURE_SSL_REDIRECT] map[name:IS_BEHIND_PROXY] map[name:SECRET_KEY] map[name:SAML_ENTITY_ID] map[name:SAML_ACS_URL] map[name:SAML_X509_CERT] map[name:SAML_ATTR_PERMANENT_ID] map[name:SAML_ATTR_FIRST_NAME] map[name:SAML_ATTR_LAST_NAME] map[name:SAML_ATTR_EMAIL] map[name:PRIMARY_DB] map[name:POSTHOG_POSTGRES_HOST] map[name:POSTHOG_POSTGRES_PORT] map[name:POSTHOG_DB_USER] map[name:POSTHOG_DB_NAME] map[name:POSTHOG_DB_PASSWORD] map[name:USING_PGBOUNCER] map[name:CLICKHOUSE_HOST] map[name:CLICKHOUSE_CLUSTER] map[name:CLICKHOUSE_DATABASE] map[name:CLICKHOUSE_USER] map[name:CLICKHOUSE_PASSWORD] map[name:CLICKHOUSE_SECURE] map[name:CLICKHOUSE_VERIFY] map[name:EMAIL_HOST] map[name:EMAIL_PORT] map[name:EMAIL_HOST_USER] map[name:EMAIL_HOST_PASSWORD] map[name:EMAIL_USE_TLS] map[name:EMAIL_USE_SSL] map[name:DEFAULT_FROM_EMAIL] map[name:CAPTURE_INTERNAL_METRICS] map[name:HELM_INSTALL_INFO] map[name:SITE_URL]]. Retrying attempt #5 at 4:17AM.
```
