### ISSUE TITLE
hpa isn't working

### ISSUE THREAD

**Issue by sharon-asana** [PostHog/charts-clickhouse#420]
## Bug description
I'm a newbie with helm charts and kubernetes in general,
I've noticed that when I have the HPA for any of the deployment enabled there's HPA requests are missing.

## Expected behavior
I expected to have the hpa targets set properly

## Actual behavior
```kubectl get hpa -n posthog-karpenter                    
NAME                REFERENCE                      TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
posthog-events      Deployment/posthog-events      <unknown>/60%   1         10        1          8m38s
posthog-pgbouncer   Deployment/posthog-pgbouncer   <unknown>/60%   1         10        1          8m38s
posthog-plugins     Deployment/posthog-plugins     <unknown>/60%   1         10        1          8m38s
posthog-web         Deployment/posthog-web         <unknown>/60%   1         10        1          8m38s
posthog-worker      Deployment/posthog-worker      <unknown>/60%   1         10        1          8m38s
```

## How to reproduce

1. run the usual `helm upgrade --install -f .values.yaml --timeout 20m --create-namespace --namespace posthog-karpenter posthog posthog/posthog --wait --wait-for-jobs --debug`

## Environment
I'm using EKS with an arch/linux local environment.

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): AWS
- [ ] k8s version (server version from `kubectl version`): Client Version: v1.24.1
- [ ] Chart version/commit (`helm list -n posthog`): 20.2.2
- [ ] Posthog version: 1.36

## Additional context
I would suggest adding the following to each deployment the following (in this example it's the posthog-events deoployment):
** under .spec.template.spec.containers[]
```
{{- if .Values.events.hpa.enabled }}
  resources:
          requests:
            memory: {{ .Values.events.hpa.requests.memory}}
            cpu: {{ .Values.events.hpa.requests.cpu}}
          limits:
            memory: {{ .Values.events.hpa.limits.memory}}
            cpu: {{ .Values.events.hpa.limits.cpu}}
  {{- end }}
```

while adding the following to the values:
```
# capcity
    requests:
      memory: 512M
      cpu: 500m # half a vCPU
    
    limits:
      memory: 1024M
      cpu: 1000m # one vCPU
```

Thanks,
Sharon.

**Comment by guidoiaquinti** [comment]
👋 Hey Sharon, thank you for your report. 

The issue you've been experiencing is because you didn't set any resource limits for the deployments (see the [official k8s documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for more info). 

Here's an example config for the web deployments you can use to have a working HPA:
```
web:
  enabled: true
  resources:
    requests:
      cpu: 0.25
      memory: 256M
    limits:
      cpu: 1
      memory: 512M
  hpa:
    enabled: true
 ```
