### ISSUE TITLE
Unable get trends of Unique Users.

### ISSUE THREAD

**Issue by yog27ray** [PostHog/charts-clickhouse#485]
While creating trends with unique users I am getting errors in api response. But when I change it from "unique users" to "Total users" everything is working fine. I even tried doing a fresh deployment but still facing the same issue.

Error in API
```
URL: https://abc.xyz.com/api/projects/2/insights/trend/?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&interval=week&actions=%5B%5D&new_entity=%5B%5D&display=ActionsLineGraph&properties=%5B%5D

Response: {"type":"server_error","code":"error","detail":"A server error occurred.","attr":null}
```

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): GCP
- [ ] k8s version (server version from `kubectl version`): v1.23.5-gke.1503
- [ ] Chart version/commit (`helm list -n posthog`): 1.37.1  
- [ ] Posthog version: 1.37.1

values.yml

```
cloud: "gcp"
ingress:
  hostname: abc.xyz.com
  gcp:
    ip_name: "posthog"
  nginx:
    enabled: true

https://user-images.githubusercontent.com/9247177/178695838-55e635a9-3682-48d7-bb1a-a79b68e49c35.mov



cert-manager:
  enabled: true

# Use larger storage for stateful services
clickhouse:
  enabled: true
  layout:
    shardsCount: 3
    replicasCount: 2
#  nodeSelector:
#    diskType: ssd
#    nodeType: fast
  persistence:
    enabled: true
    size: 100Gi

postgresql:
  enabled: true

https://user-images.githubusercontent.com/9247177/178697346-5f1d7cca-a0b4-42af-86d4-1f51815ac255.mp4


  persistence:
    enabled: true
    size: 60Gi
#  master:
#    nodeSelector:
#      diskType: ssd
#      nodeType: fast
  resources:
    requests:
      cpu: 3000m
      memory: 4Gi
    limits:
      cpu: 3000m
      memory: 4Gi

kafka:
  enabled: true
#  nodeSelector:
#    diskType: ssd
#    nodeType: fast
  persistence:
    enabled: true
    size: 50Gi
  logRetentionBytes: _22_000_000_000
  resources:
    requests:
      cpu: 2000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi

#redis:
#  master:
#    nodeSelector:
#      diskType: ssd
#      nodeType: fast

#zookeeper:
#  nodeSelector:
#    diskType: ssd
#    nodeType: fast


# Enable horizontal pod autoscaling for stateless services
events:
  hpa:
    enabled: true
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources:  
    requests:
      cpu: 1500m
      memory: 2Gi
    limits:
      cpu: 1500m
      memory: 2Gi

pgbouncer:
  hpa:
    enabled: true
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources:
    requests:
      cpu: 500m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 100Mi

plugins:
  hpa:
    enabled: true
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources:
    requests:
      cpu: 1500m
      memory: 2Gi
    limits:
      cpu: 1500m
      memory: 2Gi
web:
  hpa:
    enabled: true
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi

worker:
  hpa:
    enabled: true
    cputhreshold: 60
    minpods: 1
    maxpods: 10
  resources:                                    
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi

# Email
email:
  host: smtp.gmail.com
  port: 587
  user: xxxx@xxx
  password: xxxxx
```

https://user-images.githubusercontent.com/9247177/178697426-3a152510-5b5c-454c-a1e8-328f64178c6d.mp4
