### ISSUE TITLE
As of helm chart >=25.0.0, pgbouncer no longer allows TLS connections (readiness check, helm upgrade fails)

### ISSUE THREAD

**Issue by paulcwatts** [PostHog/charts-clickhouse#493]
## Bug description

Previous to helm chart 25.0.0 and the change to the pgbouncer container image, we were allowed to require a TLS connection to Postgres using the pgbouncer config:

```yaml
pgbouncer:
  env:
  - name: SERVER_TLS_SSLMODE
    value: "your_value"
```

As discussed here: https://github.com/PostHog/charts-clickhouse/pull/198#issuecomment-1028777169

When upgrading to helm chart 25.1.4, I updated my config to match the new pgbouncer environment settings (adding the `PGBOUNCER_` prefix). When that happened, the posthog web app was able to connect to Postgres; however, the pgbouncer readiness/liveness check fails. This doesn't the pgbouncer pod to become ready, and therefore the helm upgrade fails.

## Expected behavior

Previously we were able to set sslmode to "prefer" or "require".  

## Actual behavior

We can't do that anymore, because the pgbouncer liveness/readiness checks fail. The web app, however, is actually up and running.

## How to reproduce

1. Set this config in your helm values:

```yaml
pgbouncer:
  env:
  - name: PGBOUNCER_SERVER_TLS_SSLMODE
    value: "require"
```
2. Try to install the helm chart

## Environment

- [X] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): AWS EKS
- [X] k8s version (server version from `kubectl version`): v1.22.10-eks-84b4fe6
- [X] Chart version/commit (`helm list -n posthog`): posthog-25.1.4
- [X] Posthog version: 1.37.1

## Additional context

Similar issues happened in this Slack thread: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1651248022483489

**Comment by guidoiaquinti** [comment]
👋 Hi! By overriding `pgbouncer.env` you are also overriding the chart defaults. I think your values.yaml should look like:

```
pgbouncer:
  env:
    - name: PGBOUNCER_PORT
      value: "6543"
    - name: PGBOUNCER_MAX_CLIENT_CONN
      value: "1000"
    - name: PGBOUNCER_POOL_MODE
      value: transaction
    - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
      value: extra_float_digits
    - name: PGBOUNCER_SERVER_TLS_SSLMODE
    value: "require"
  ```
