### ISSUE TITLE
Add additional configuration to externalKafka

### ISSUE THREAD

**Issue by logand22** [PostHog/charts-clickhouse#595]
### Proposed change
I'd like the ability to configure Kafka security protocol as well as SASL parameters via the `externalKafka` helm chart values. 

For example:

```yaml
# Ignored if `kafka.enabled` is set to `true`. 
externalKafka:
  # - External Kafka brokers. Multiple brokers can be provided as array/list.
  brokers: []
  # - External Kafka security protocol.
  securityProtocol: ""
  # - External Kafka authentication SASL Mechanism.
  saslMechanism: ""
  # - External Kafka SASL user.
  saslUser: ""
  # - External Kafka SASL password. Either this or `externalKafka.existingSecret` must be set.
  saslPassword: ""
  # - Name of an existing Kubernetes secret object containing the Kafka SASL password.
  existingSecret: ""
  # - Name of the key pointing to the password in your Kubernetes secret
  existingSecretPasswordKey: "password"
```

### Alternative options
You can add the environment variables as defined in [PostHog data sources](https://github.com/PostHog/posthog/blob/106db8669bb8064c1d8b507ff5fc40dd4116ce15/posthog/settings/data_stores.py#L134-L137) directly through the `env` configuration section in `.values.yaml`.

This doesn't allow the user to specify a secret for the password or the ClickhouseInstallation.

## Additional context
I'm deploying PostHog with [Amazon MSK](https://aws.amazon.com/msk/) and would like to use SASL/SCRAM authentication but don't want to have password exposed in helm chart values. Additionally, I had to look into PostHog source code to understand how to configure this. Having these values in the helm chart could improve the UX for this chart.
