### ISSUE TITLE
GCP deployment results in 502 http error

### ISSUE THREAD

**Issue by mands** [PostHog/charts-clickhouse#94]
## Bug description

Upon installing to GCP with the default values in the README.md, I get a 502 upon going to the main URL

![image](https://user-images.githubusercontent.com/1010043/128523957-67209516-db30-4b04-bd58-728d635e11cd.png)

### helm command

```bash
$ helm --kube-context analytics --namespace posthog1 install posthog posthog/posthog --values ./posthog-values-v2.yaml --set email.password=$SENDGRID_API_KEY --atomic --create-namespace
```

### values

```yaml
cloud: "gcp"
ingress:
  hostname: xyz.example.com
  nginx:
    enabled: false
certManager:
  enabled: false
metrics:
  enabled: false
email:
  from_email: posthog@example.com
  host: smtp.sendgrid.net
  user: apikey
```

- I created an External IP in the GCP console, as per the docs, which appears to be connected to the K8S node port

![image](https://user-images.githubusercontent.com/1010043/128524287-8d6e5f83-d9f4-4e45-b41c-0bab4ed1cabd.png)

- I have an Google managed SSL cert which seems to have provisioned, hence DNS is working

```bash
$ gcloud beta compute ssl-certificates list
NAME                                                TYPE          CREATION_TIMESTAMP             EXPIRE_TIME                    MANAGED_STATUS
k8s2-cr-mi7kcees-a0bsfajor9b9gf2a-19c53f806b9b9baf  SELF_MANAGED  2021-06-20T23:39:15.697-07:00  2021-09-18T22:31:28.000-07:00
mcrt-291b0d5a-888d-4ac4-8d00-6dc563537402           MANAGED	  2021-08-06T06:53:02.540-07:00  2021-11-04T06:53:05.000-07:00  ACTIVE
    xyz.example.com: ACTIVE
```

- The `posthog NodePort` seems to be up
```bash
$ kubectl get svc posthog --namespace posthog1
NAME      TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
posthog   NodePort   10.72.0.5    <none>        8000:30984/TCP   19m
```

## Expected behavior

- The posthog home page is returned

## Environment

- [ ] Deployment platform (gcp/aws/...): GCP
- [ ] Chart version/commit: 3.3.0
- [ ] Posthog version: default for chart

## Additional context

- I'm using `posthog1` as a namespace, as I'm unable to delete the initial `posthog` namespace due to the `ClickHouseInstallation` operator not deleting when running `helm uninstall`
